Update template code to reflect new Clojars verified group policy
technomancy/leiningen pull request #2734
Opened 2021-03-21 20:42 UTC by technomancy

Clojars is changing the rules around what kind of groups are allowed to be created: https://github.com/clojars/clojars-web/wiki/Verified-Group-Names

In particular, the current system of using the template name as the group-id and "lein-template" as the artifact-id will no longer be supported, since group-ids for new libraries must be verified using a reverse-domain scheme. The new scheme is to use a fully-qualified template name such as `us.technomancy/liquid-cool` which results in a lookup for the jar at `us.technomancy/lein-template.liquid-cool`.

This PR updates:
* the template used to create new templates
* the documentation around creating new templates
* the `new` task which looks for templates

Also includes a bonus commit removing assumptions in the template around what code hosting site is used.

2021-03-21 20:43 UTC, technomancy commented
Oops; haha, forgot to update the tests.

2021-03-24 01:33 UTC, seancorfield requested changes
Sorry, I didn't realize my "comments" became a "review" and were still pending.

2021-03-27 18:02 UTC, technomancy commented on resources/leiningen/new/template/temp.clj
> +(ns leiningen.new.{{group-id}}.{{artifact-id}}
Ah yeah I think that's true. I was thinking about the possibility of conflicts across things you might already have on the classpath (plugins etc) but since it's already prefixed with `leiningen.new.` that's probably not a concern.

2021-03-27 18:08 UTC, technomancy commented on src/leiningen/new.clj
> +         (debug (str e)))))
Just wanted to make sure there was a way to see the error here instead of silently swallowing it. The return value is nil in either case.

2021-03-27 18:23 UTC, technomancy commented on src/leiningen/new.clj
> +    (let [[group-id artifact-id] ((juxt namespace name) (symbol template-name))]
You know what I just assumed that two slashes in a symbol would be rejected by the reader; turns out that's not the case. It'll be accepted as a symbol but it still won't be resolveable as a dependency, so I think we're safe here.

2021-03-27 18:25 UTC, technomancy commented on src/leiningen/new/template.clj
> +    (main/warn (str "Template names must use a group-id to conform with new"
Yeah that's reasonable behavior for a tool that's starting from scratch, but I think it's better to behave differently here given the history.

2021-03-27 18:31 UTC, technomancy commented on src/leiningen/new/template.clj
> +              :group-id (namespace sym)
No I think you're right that putting the group-id in the namespace name of the template isn't buying us anything; I'll get rid of that. Thanks for pointing this out.

2021-03-27 19:09 UTC, seancorfield approved these changes
Modulo the test failure due to the new naming for the liquid-cool template (the new VGN version doesn't exist on Clojars), this looks good and matches `clj-new` closely enough that I think we're good to go. Thanks!

2021-03-27 23:28 UTC, technomancy commented
Thanks for the second pair of eyes!

2021-03-27 23:29 UTC, merged